title: Bhavesh Parkhe # your name (or website title) here
logo: "/images/Casual.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br>
  Masters in Mechanical Engineering
  University of Masscussetts Amherst<br> 
  <br><a href="/about">About me</a><br>
  <a href="/projects_page">Projects</a><br>
  <a href="https://www.linkedin.com/in/bparkhe/">View My LinkedIn Profile</a><br>
  <a href="/pdf/BhaveshParkhe_Resume.pdf">View My Resume</a> <br>  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
  