title: Bhavesh Parkhe # your name (or website title) here
logo: "/images/Casual.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br>
  Control Systems + Autonomous Vehicles + Aspiring Minimalist<br>
  <br>
  MS in Mechanical Engineering<br>
  University of Masscussetts Amherst<br> 
  <br><a href="/index">Home</a><br>
  <a href="/about">About me</a><br>
  <a href="/projects_page">Projects</a><br>
  <a href="/resume">Resume/CV</a><br>
  <a href="https://www.linkedin.com/in/bparkhe/">LinkedIn Profile</a><br>
  <a href="https://github.com/bparkhe">Github Profile</a><br>
  <a href="https://scholar.google.com/citations?user=BCjwHNwAAAAJ&hl=en">Google Scholar</a><br>    
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
  