title: Bhavesh Parkhe # your name (or website title) here
logo: "/images/Casual.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 

  <br>Masters in Mechanical Engineering<br>
  <br>University of Masscussetts Amherst<br> 
  
  <a href="https://www.linkedin.com/in/bparkhe/">View My LinkedIn Profile</a> 
  
  <a href="/pdf/BhaveshParkhe_Resume.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
